fix bug
WarHatch/PEEKT pull request #27
Opened 2019-05-27 20:39 UTC by PauliusGrigaliunas

2019-05-27 20:48 UTC, WarHatch requested changes
Unsure about stability

2019-05-27 20:48 UTC, WarHatch commented on TravelAgent/TravelAgent/DataContract/Responses/EmployeeTravelResponse.cs
> +    }
O čia neturėtų dar būt `bool confirm`?

2019-05-27 20:48 UTC, WarHatch commented on TravelAgent/TravelAgent/Controllers/EmployeeTravelController.cs
> +                    };
What value is set for Travel?

2019-05-27 21:05 UTC, WarHatch commented
GetById and GetAll EmployeeTravel still return null for hotels and transports 😭

2019-05-28 17:06 UTC, WarHatch commented on TravelAgent/TravelAgent/DataContract/Responses/EmployeeTravelResponse.cs
> +    }
@PauliusGrigaliunas last one remaining

2019-05-28 17:14 UTC, PauliusGrigaliunas commented on TravelAgent/TravelAgent/DataContract/Responses/EmployeeTravelResponse.cs
> +    }
I didn't use it, yet

2019-05-28 17:22 UTC, WarHatch approved these changes
https://media.giphy.com/media/l0HTYUmU67pLWv1a8/giphy.gif

2019-05-28 17:22 UTC, merged